// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/admin","redirect":"/admin/sub-page","parentId":"3","id":"4"},"5":{"path":"/admin/sub-page","name":"sub-page","parentId":"3","id":"5"},"6":{"name":"list.file-center","icon":"table","path":"/center","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"list.img-list","icon":"table","path":"/imgList","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/imgSegament/:id","name":"list.img-segament","icon":"smile","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/","redirect":"/center","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"*","layout":false,"id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import( './EmptyRoute')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__FileCenter__index" */'@/pages/FileCenter/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__ImgList__index" */'@/pages/ImgList/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Segament__index" */'@/pages/Segament/index.tsx')),
'9': React.lazy(() => import( './EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/xuzhuoqing/kone-feature-recongition/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/xuzhuoqing/kone-feature-recongition/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
