// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from '/Users/xuzhuoqing/kone-feature-recongition/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/xuzhuoqing/kone-feature-recongition/node_modules/@ant-design/icons/es/icons/TableOutlined';
import SmileOutlined from '/Users/xuzhuoqing/kone-feature-recongition/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { CrownOutlined, TableOutlined, SmileOutlined };
